version: '3'
services:
   machinelearn:
      privileged: true
      restart: always
      image: tensorflow/tensorflow
      ports:
        - 8888:8888
   rocketchat:
      image: rocketchat/rocket.chat:latest
      restart: always
      depends_on:
        - mongo
   mongo:
    image: mongo:latest
    restart: always
   chatbot:
      image: rocketchat/hubot-rocketchat:latest
      restart: always
