version: '3'
services:
   machinelearn:
      privileged: true
      restart: always
      image: tensorflow/tensorflow
      ports:
        - 8888:8888
   rocketchat:
      image: rocketchat/rocket.chat:latest
      restart: always
      environment:
        - PORT=3000
        - ROOT_URL=http://localhost:3000
        - MONGO_URL=mongodb://mongo:27017/rocketchat
        - MONGO_OPLOG_URL=mongodb://mongo:27017/local
        - MAIL_URL=smtp://smtp.email
      ports:
        - 3000:3000
      depends_on:
        - mongo
   mongo:
      image: mongo:latest
      restart: always
   mongo-init-replica:
      image: mongo:latest
      command: 'mongo mongo/rocketchat --eval "rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''localhost:27017'' } ]})"'
    depends_on:
      - mongo
   chatbot:
      image: rocketchat/hubot-rocketchat:latest
      restart: always
      depends_on:
        - rocketchat 
